# This is a basic workflow to help you get started with Actions

name: k8-rebuild
env:
  AWS_DEFAULT_REGION: eu-west-1
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      create_ova:
        description: Create OVA
        default: "false"
        required: true
  push:
    branches: [ main ]
    paths-ignore:
      - 'aws-jmeter-test-engine'
      - 'gp-load-balancer'
      - 'GW-proxy'
      - 'icap-infrastructure'
      - 's-k8-proxy-rebuild'
      - '.github/workflows/icap-server.yaml'
      - '.github/workflows/proxy-rebuild.yaml'
      - '.github/workflows/proxy-rebuild-ova.yaml'
      - '.github/workflows/haproxy.yaml'
      - '.github/workflows/monitoring.yaml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ami:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
    - uses: actions/checkout@v2
      with:
        submodules: true

    # - name: Update submodules
    #   run: |
    #     git submodule foreach git fetch
    #     git submodule foreach git pull origin main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    # build artifact
    - name: Setup Packer
      run: |
        cd k8-rebuild/packer
        curl -o packer.zip https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip
        unzip -o packer.zip
        sudo mv packer /usr/local/bin
        cd ../
        
    - name: Build AMI/OVA
      run: |
        cd vmware-scripts/packer
        cp -r target/filedrop/* setup/
        chmod +x ova-check.sh
        cat > setup/env <<EOF
        SSH_PASSWORD=${{ secrets.ICAP_SSH_PASSWORD }}
        BRANCH=sow_version
        EOF
        sed -i 's/<vm_name>/k8-rebuild-centos/g' ova-export.json
        RANDOM_STR=${{ github.sha }}-${{ github.run_number }}
        packer build -color=false -on-error=cleanup -var github_sha=${RANDOM_STR} -var vm_name=k8-rebuild-centos -var create_ova=${{ github.event.inputs.create_ova }} -var region=${{ env.AWS_DEFAULT_REGION }} -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws-ami.json

  deploy-ami:
    runs-on: ubuntu-latest
    needs: build-ami
    steps:
      - name: Get the current instance id
        id: get_id
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        run: |
          # instance_id="${{ steps.deploy.outputs.instance_id }}"
          instance_id=$(aws ec2 describe-instances --filters 'Name=tag:Name,Values=dev-k8-rebuild' "Name=instance-state-name,Values=running" --output text --query 'Reservations[*].Instances[*].InstanceId')
          echo ::set-output name=instance_id::$instance_id
          
      - name: Deploy AMI to dev
        id: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        run: |
          RANDOM_STR=${{ github.sha }}-${{ github.run_number }}
          ami_id=$(aws ec2 describe-images --filters "Name=name,Values=k8-rebuild-centos-${RANDOM_STR}" --query 'Images[*].[ImageId]' --output text)
          result=$(aws ec2 run-instances --image-id $ami_id --count 1 --instance-type t2.large --key-name packer --security-group-ids sg-0120400d5eefb0b9e --tag-specifications 'ResourceType=instance, Tags=[{Key=Name,Value=dev-k8-rebuild-centos}, {Key=Delete,Value=No},{Key=Scope,Value=filedrop}, {Key=Team, Value=k8-proxy/k8-rebuild}, {Key=Owner, Value=githubactionAMIpacker}, {Key=AMI_Name, Value=k8-rebuild-${{ github.sha }}}]')
          sleep 15m
          instance_id=$(echo $result | jq -r ".Instances[0].InstanceId")
          echo "$instance_id is created."
          instance_description=$(aws ec2 describe-instances --instance-ids $instance_id)
          instance_state=$(echo $instance_description | jq -r ".Reservations[0].Instances[0].State.Name")
          echo "Instance state is $instance_state"
          if [[ "$instance_state" != "running" ]];then
              echo "EC2 instance $instance_id created from AMI has failed to start in time, terminating the instance." 
              aws ec2 terminate-instances --instance-ids $instance_id
              exit -1
          fi
          instance_ip=$(echo $instance_description | jq -r ".Reservations[0].Instances[0].PublicIpAddress")
          echo "Access the application at http://${instance_ip}"
          echo ::set-output name=instance_ip::$instance_ip
          echo ::set-output name=instance_id::$instance_id
          echo ::set-output name=ami_id::$ami_id

      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          repository: k8-proxy/vmware-scripts
          path: vmware-scripts

      - name: Run tests on the VM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        run: |
          instance_id="${{ steps.deploy.outputs.instance_id }}"
          instance_ip="${{ steps.deploy.outputs.instance_ip }}"
          ami_id="${{ steps.deploy.outputs.ami_id }}"
          cd vmware-scripts/HealthFunctionalTests/filedrop
          npm install
          sed -i -r "s/([0-9]{1,3}\.){3}[0-9]{1,3}/$instance_ip/g" cypress/integration/filedrop.spec.js
          npm test
          echo "Tests are successfully on the new instance, terminating old instance."
          aws ec2 create-tags --resources $ami_id --tags Key=Test_Result,Value=Success
          instance_id="${{ steps.get_id.outputs.instance_id }}"
          if [[ ! -z "$instance_id" ]]; then
            echo "$instance_id" | while IFS= read -r line ; do aws ec2 terminate-instances --instance-ids $line || true; done
          fi

      - name: Delete instance if tests fail
        if: ${{ failure() }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        run: |
          echo "Failed integration tests, terminating the newly deployed VM"
          instance_id="${{ steps.deploy.outputs.instance_id }}"
          ami_id="${{ steps.deploy.outputs.ami_id }}"
          aws ec2 terminate-instances --instance-ids $instance_id
          aws ec2 create-tags --resources $ami_id --tags Key=Test_Result,Value=Failed
